#!/bin/bash  -x

# Leon Ramos
# leon.ramos@creadoresdigitales.com
# 2017

#    Este programa es software libre: Usted puede redistribuirlo y/o modificarlo
#    bajo los terminos de la licencia de uso publico general (GNU General Public License) como
#    aparece publicada por la Fundacion de Software Libre, ya sea la version 3 de dicha licencia, o 
#    a su discresion, cualquier version posterior.

#    Este programa es distribuido con el objetivo de ser útil, pero sin ninguna garantia,
#    inclusive sin las garantias implicitas en la comercializacion o adecuadas para cualquier proposito especifico.
#    Vea la licencia de uso publico general "GNU General Public License" para mas detalles.

#    Si no recibe una copia de la licencia "GNU General Public License" junto con este codigo,
#    favor de referirse a la siguiente direccion: <http://www.gnu.org/licenses/>.

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

export TEXTDOMAINDIR=./bash/locale
export TEXTDOMAIN=veritech

#import libraries
. ./bash/libs/os_detection.sh
. ./bash/libs/i18n_echo.sh
. ./bash/libs/check_root.sh
. ./bash/libs/dependencies.sh
. ./bash/libs/check_first_run.sh
. ./bash/libs/dialog/common.sh
. ./bash/libs/dialog/welcome.sh
. ./bash/libs/dialog/easy-rsa.sh
. ./bash/libs/dialog/server_data.sh
. ./bash/libs/dialog/cert_data.sh

D=false
SCRIPT=$0
COUNTRIES=./data/countries.csv

usage () {
  echo "Usage: $0"
  echo " Poner uso aqui"
}

while getopts "v" optname ; do
  case $optname in
  "v")  D=true
        echoD "getopts_debug_enabled"
        ;;
  "?")
        D=true
        error "getopts_unknown_option"
        usage
        ;;
  esac
done

echoD "debug_current_platform" "$ARCH $OS $VER"
supported_platform

check_root

dialog_welcome

install_dependencies

check_first_run
